### ISSUE TITLE
[Feature Request] Uninstall charts by regexp / by time

### ISSUE THREAD

**Issue by stackia** [brickdoc/app-engine#1]
An example use case is to cleanup long-lived preview env deployments.

For some reasons, a PR might get deployed but didn't cleanup the deployment after PR closed. If we can schedule to run this action periodically to uninstall charts that matches a specific regexp and have lived for a specific duration, it should help GC those unused deployments.

Expected usage:

```yaml
name: GC Outdated Preview Deployments
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * 0-4'

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - name: Uninstall charts
        uses: brickdoc/app-engine@v1.beta3
        with:
          name: '/^brickdoc-preview-pr\d+/'
          task: 'remove'
          olderThan: '2d'
```

**Comment by 0xDing** [comment]
```yaml
---
name: PR Preview Environment Garbage Collection
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  app_engine_gc:
    name: Garbage Collection of Unused Container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.XXX_AK }}
        aws-secret-access-key: ${{ secrets.XXX_SECRET }}
        aws-region: xxxxxxx
    - name: Update EKS configure
      run: aws eks update-kubeconfig --name xxx
    - name: get helm deployments
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPS_PREFIX: xxxx-preview-pr
      run: |
        OPENED_PR=$(gh pr list -s open --json number | jq 'map(.number)|join(",")')
        echo "Opened PRs: $OPENED_PR"
        OPENED_HELM=$(helm list -n cicd -f "$APPS_PREFIX.+" -o json  | jq "map(.name|sub(\"$APPS_PREFIX\";\"\"))|join(\",\")")
        echo "Opened Helm releases: $OPENED_HELM"
        jq -n -r "{gh:$OPENED_PR|split(\",\"),helm:$OPENED_HELM|split(\",\")}|.helm-.gh|map(\"$APPS_PREFIX\(.)\") |.[]" | while read i; do
          echo "uninstall $i...."
          helm uninstall $i -n cicd
        done
```
